version: "3.9"

services:
  apigateway:
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    environment:
      HOST: apiregistercandidate
      PORT: 5001
    image: apigateway
    networks:
      - microservices
    ports:
      - 5000:5000

  apiregistercandidate:
    build:
      context: .
      dockerfile: ApiRegisterCandidate/Dockerfile
    image: apiregistercandidate
    networks:
      - microservices
    ports:
      - 5001:5001

networks:
  microservices: